### ISSUE TITLE
Wrong path to Package Settings -> Settings ->Default

### ISSUE THREAD

**Issue by chew-z** [bsoun/bang-search#1]
Cool plugin! :)

There is something wrong with Default Settings (Sublime Text 3, OSX 10.10)

FileNotFoundError: [Errno 2] No such file or directory: '/Users/rrj/Library/Application Support/Sublime Text 3/Packages/bang-search/bang_search.sublime-settings'

**Comment by bsoun** [comment]
Thanks, 
Yes, the settings are unavailable directly because the package is packed.
You can see detail here: 
[Customizing Packages](https://packagecontrol.io/docs/customizing_packages)

You have to manually create the file with the following content : 
[bang_search.sublime-settings](https://raw.githubusercontent.com/bsoun/bang-search/master/bang_search.sublime-settings)

I will probably make a new release in the next weeks, with a unpacked version, and with a new "bang", the qwick of the french search engine Qwant :
- [What is Qwant](https://en.wikipedia.org/wiki/Qwant)
- [Qwick](https://www.qwant.com/qwick)

**Comment by chew-z** [comment]
Thank you.

If I could suggest anything it would be useful to have an option to choose a browser. like 'webbrowser.get('firefox').open_new_tab(searchUrl)'. Otherwise it always defaults to Safari on my Mac.

**Comment by bsoun** [comment]
It will be in the coming release.

**Comment by bsoun** [comment]
Here is the the new release
