### ISSUE TITLE
[Bug] bang_search_input + AutoHotkey

### ISSUE THREAD

**Issue by Kristinita** [bsoun/bang-search#5]
### 1. Summary

I can not set custom hotkey use [**AutoHotkey method for hotkeys**](http://superuser.com/a/1169778/572069).

### 2. Expected behavior

Like `bang_search_input default` and `bang_search AutoHotkey`

![Bang Search](http://i.imgur.com/OvwZLeq.gif)

### 3. Actual behavior

`bang_search_input AutoHotkey`

### 4. Settings

Part of my `bang_search.sublime-settings` file:

```json
"&g.ru": {
    "type": "qwant",
    "caption": "Google Russia"
},
```

Part of my `User\Default (Windows).sublime-keymap` file:

```json
{
  "keys": ["ctrl+alt+shift+super+f5"],
  "command": "bang_search_input",
  "args": {"search_method": "&g.ru"}
},
```

Part of my `Mini-scripts.ahk` file:

```autohotkey
#enter::
Send {WIN up}
Send {ENTER up}
Send !^+#{F5}
```

### 5. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I use [**@BladeMight method**](http://superuser.com/a/1169778/572069) for [**change native Windows 10 hotkeys**](https://support.microsoft.com/en-us/help/12445/windows-keyboard-shortcuts) to custom hotkeys for Sublime Text. So far, the method worked for all Sublime Text plugins exclude Bang.

See my GIF. If I press <kbd>Ctrl+Alt+Shift+Super+F5</kbd>, command `bang_search_input` successfully run for me. If I press <kbd>Super+Enter</kbd> for `bang_search` command, command successfully run for me. But if I press <kbd>Super+Enter</kbd> for `bang_search_input` command, Bang quick panel quickly appears and disappears

I try change `&g.ru`, <kbd>Ctrl+Alt+Shift+Super+F5</kbd> and <kbd>Super+Enter</kbd> to other values, but I get same behavior.

### 6. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126
**AutoHotkey:**
1.1.24.04

Thanks.

**Comment by bsoun** [comment]
Hello,
Unfortunately, I'm unable to reproduce, because I'm working only with linux at the moment.
It seems that the input panel receive the Enter from your hotkey. Can you test these things 

- Modify your autohotkey setup: <kbd>Super</kbd>+<kbd>B</kbd> for example
- In sublime text console type the following command to intercept the key pressed :
```sublime.log_input(True)``` to confirm the real keys' sequence received
- Install textPastry plugin, and bind the _Text Pastry: Menu_ with your hotkey. This command launch an input panel and like the direct Bang Input Search Panel disappeared with Enter.

**Comment by Kristinita** [comment]
I find a problem. [**This conflict script**](https://github.com/ahkscript/SublimeAutoHotkey/issues/40#issuecomment-265702557) add `command: hide_panel {"cancel": true}` after `command: bang_search_input {"search_method": "&g.ru"}` command.

Thanks. Sorry at an issue.
